[variables]
    NIXPACKS_PYTHON_VERSION = "3.11"

[phases.setup]
    nixPkgs = ['python311', 'firefox', 'geckodriver']

[phases.install]
    cmds = [
        'pip install -r requirements-railway.txt || pip install flask==3.1.2 flask-sqlalchemy==3.1.1 gunicorn==23.0.0 psycopg2-binary==2.9.10 selenium==4.35.0 webdriver-manager==4.0.2 qrcode==8.2 pillow==11.3.0 email-validator==2.3.0 werkzeug==3.1.3'
    ]

[phases.build]
    cmds = [
        'mkdir -p static/css static/js',
        'touch static/css/custom.css',
        'echo "console.log(\"App ready\");" > static/js/main.js'
    ]

[start]
    cmd = 'gunicorn --bind 0.0.0.0:$PORT --workers 1 --threads 8 --timeout 0 main:app'