[build]
builder = "nixpacks"

[deploy]
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 2

[env]
RAILWAY_ENVIRONMENT = "production"
DISPLAY = ":99"